# Generated by Django 4.1 on 2022-09-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('IDemp', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefono', models.CharField(max_length=20)),
                ('FechaCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=100, unique=True)),
                ('NIT', models.IntegerField()),
                ('Ciudad', models.TextField(max_length=100)),
                ('Direccion', models.TextField(max_length=100)),
                ('Telefono', models.CharField(max_length=50)),
                ('SectorProductivo', models.CharField(max_length=50)),
                ('FechaCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Roll', models.TextField(max_length=50)),
                ('FechaCreacion', models.DateField()),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transferencias.empresa')),
                ('IDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transferencias.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('IDT', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('FechaTransaccion', models.DateField(auto_now=True)),
                ('Concepto', models.TextField(max_length=1000)),
                ('Monto', models.IntegerField(max_length=100)),
                ('TipoTransferencia', models.CharField(max_length=100)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transferencias.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transferencias.empresa'),
        ),
    ]
